CREATE TABLE Pedidos (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Cedula NVARCHAR(20) NOT NULL,
    DireccionEntrega NVARCHAR(255) NOT NULL,
    FechaPedido DATETIME DEFAULT GETDATE(),
    Total DECIMAL(18,2) NOT NULL
);